#!/bin/bash

ghc -O2 -i/C:/Users/Owner/Dropbox/CS/AI/FARG/fluidity:C:/Users/Owner/Dropbox/CS/AI/FARG/fluidity/SeekWhence:C:/Users/Owner/Dropbox/CS/AI/FARG/fluidity/SeekWhence/formulas:C:/Users/Owner/Dropbox/CS/AI/FARG/fluidity/SeekWhence/agents -o $1 $1.hs

